/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaDsa;

import JavaDsa.Trees.BinarySearchTree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        BinarySearchTree tree = new BinarySearchTree();

        tree.insert(8);
        tree.insert(3);
        tree.insert(10);
        tree.insert(1);
        tree.insert(6);
        tree.insert(14);
        tree.insert(4);
        tree.insert(7);
        tree.insert(13);

        System.out.println(tree.breadthFirstSearch(8));






    }
}
