/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaDsa;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {



        //System.out.println(leet.traverseSum(leet.getRoot(),1,14));






    }
}
